spring:
  profiles:
    active: local
---
spring:
  profiles: local
  kafka:
    template:
      default-topic: library-events-2
    producer:
      bootstrap-servers: localhost:9093,localhost:9094,localhost:9095
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 10
    admin:
      properties:
        bootstrap.servers: localhost:9093,localhost:9094,localhost:9095
---
spring:
  profiles: dev
  kafka:
    producer:
      bootstrap-servers: dev:9092,dev:9093,dev:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSeializer
      value-serializer: org.apache.kafka.common.serialization.StringSeializer
---
spring:
  profiles: prod
  kafka:
    producer:
      bootstrap-servers: prod:9092,prod:9093,prod:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSeializer
      value-serializer: org.apache.kafka.common.serialization.StringSeializer